Mobile version update
ramrod433/Portfolio pull request #5
Opened 2022-03-18 16:57 UTC by ramrod433

This is the feature update to complete the mobile version of my Portfolio
1. Added two project grids to my works section
2. Added "About me" section with a get me button
3. Added list of credentials and languages in the footer section before the contact forms

2022-03-18 18:16 UTC, Danieldotcomcoder requested changes
Hello @ramrod433 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linter are setup correctly ✔
- No Linter Errors ✔
- Professional PR ✔

## Required Changes ♻️
_Check the comments under the review._

[OPTIONAL]: It would be better if you remove this from your Readme File so it will look more professional : ✔👍
![image](https://user-images.githubusercontent.com/87448628/159060120-caa0f759-a181-4ca2-b0f1-97b44bd33e76.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-03-18 18:16 UTC, Danieldotcomcoder commented on portfolio.html
> +        </div>
Your works section doesn't match the Figma design, you should try to stick to the design as possible, please fix this : 👍😃

![image](https://user-images.githubusercontent.com/87448628/159058160-5b75d274-1e5d-48c0-b7b5-3705e2155265.png)

Figma Design : 
![image](https://user-images.githubusercontent.com/87448628/159058329-25faa0c4-0ed4-4be6-ae58-4cc0fd571e96.png)

2022-03-18 18:16 UTC, Danieldotcomcoder commented on portfolio.html
> +      </div>
Kindly wrap this category section in a 'ul` tag and put each element as `li` tag as stated in the project requirements, so your code will be more professional

2022-03-18 18:16 UTC, Danieldotcomcoder commented on portfolio.html
> +        <h2>Terminal</h2>
The categories inside the about myself section should be inside a `ul` tag, and each one of the elements ( Languages, Frameworks, and Skills ) should be in `li` tag as stated in the requirements, Kindly fix this 👍😃

2022-03-18 21:05 UTC, Donard97 requested changes
Hi @ramrod433 , 👋  
    
_Great work on making the changes requested by a previous reviewer 👏 💯_ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 💪 

![giphy (5)](https://user-images.githubusercontent.com/74506933/158914255-c412fcfa-dc99-402d-9023-99e21aab87c9.gif)


## Highlights 🏁 

- There is no linter error ✔️ 
- Gitflow is used correctly ✔️ 
- PR is descriptive ✔️ 
- The Readme file is professional ✔️ 
- Code is clean ✔️ 
    
## Required Changes ♻️

- [ ] Kindly add the other files for linter following linters configuration [repository](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Please check the comments under the review.
    
## Optional suggestions
    
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
    
**Cheers and Happy coding!👏👏👏**
    
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
    
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
    
------
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
 ```

2022-03-18 21:05 UTC, Donard97 commented on portfolio.html
> +        <h1>About me</h1>
- [ ] Well done of implementing the required changes from the other reviewer but please stick as much as you can to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471). Keep rocking 💪 

Here you have a screenshot from your project:

![image](https://user-images.githubusercontent.com/74506933/159082342-da126e5a-9540-4540-be2d-236bacf8964b.png)

Here you have a screenshot from the design:

![image](https://user-images.githubusercontent.com/74506933/159082385-6993b368-dcac-4105-b303-209dc08df585.png)

2022-03-18 21:05 UTC, Donard97 commented on portfolio.html
> +          ><img
- [OPTIONAL] I suggest you before merging to add button interactions following the Figma design:

![image](https://user-images.githubusercontent.com/74506933/159082681-f7e15718-bbb5-43ea-8dc9-2c63af29d9b8.png)

2022-03-19 00:49 UTC, Davidosky007 reviewed
Hello @ramrod433  👋,

_This is an additional review as a result of the second opinion request._

- Kindly note that setting up linters locally isn't a requirement it is used only on your local system to run linter check and fix errors if there are any, but for Github actions, linter checks you only need the  .github/workflows folder and add a copy of [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) to that folder. so as long as the linter checks are passing on Github the project is good to go.
- About sticking to the Figma design as much as possible these include the (  font, colours, images, tests, margins) [refer to the project requirements ](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20tests%2C%20margins)%20using%20the%20templates%20in%20Figma.). It is a requirement and part of this milestone learning objectives ( to be able to to parse a Figma design to create a UI)
- ## Note the content of the project doesn't have to be exactly the same as in the figma design just the ( font, colors, images, tests, margins)

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

2022-03-19 00:50 UTC, ramrod433 commented
Thank you sir

On Sat, 19 Mar 2022 at 12:49 AM, David Bassey ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hello @ramrod433 <https://github.com/ramrod433> 👋,
>
> *This is an additional review as a result of the second opinion request.*
>
>    - Kindly note that setting up linters locally isn't a requirement it
>    is used only on your local system to run linter check and fix errors if
>    there are any, but for Github actions, linter checks you only need the
>    .github/workflows folder and add a copy of
>    .github/workflows/linters.yml
>    <https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml>
>    to that folder. so as long as the linter checks are passing on Github the
>    project is good to go.
>    - About sticking to the Figma design as much as possible these include
>    the ( font, colours, images, tests, margins) refer to the project
>    requirements
>    <https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20tests%2C%20margins)%20using%20the%20templates%20in%20Figma.>.
>    It is a requirement and part of this milestone learning objectives ( to be
>    able to to parse a Figma design to create a UI)
>    - Note the content of the project doesn't have to be exactly the same
>    as in the figma design just the ( font, colors, images, tests, margins)
>
> As this was the only reason that your project was not approved it will be
> approved as soon as possible.
> Please ask for another review in your Dashboard and the next Code Reviewer
> will mark it as approved right away :)
>
> Keep rocking 🚀!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ramrod433/Portfolio/pull/5#pullrequestreview-914950642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXWMDRU7K2IQTGX42GM34G3VAUQA7ANCNFSM5RCMGBXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-19 03:29 UTC, smunozmo commented
Hi @ramrod433 , 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

💡  Just a friendly tip: If you name your main file `index.html` it will be easier to deploy your project in the future.

Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 07:41 UTC, merged